
# SEO settings
title: "Norsk Blogg fra Jonny"
title2: "space" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "norsk, blogg, norwegian, learning, nature, oslo, norway, norwegian lifestyle, images, norwegian nature"
url: https://www.jonnygrifff.no/norsk # site url
baseurl: "/norsk" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/jjegg/norsk
disqus_shortname: "hnbloggithub"
twitter_username: ""
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "John Doe"
  job      : "Software Engineer"
  bio      : "1+1=3 is always TRUE in my world, a balance between binary and reality."
  thumb    : /images/author.jpg
  email    : griffin.jonnathan@gmail.com
  url      : https://www.jonnygrifff.no
  facebook : https://www.facebook.com/jonnygrifff
  linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
twitter_card: ""
twitter_site: ""

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
